# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - bash: |
      # Install packaging dependencies
      sudo apt-get update
      sudo apt-get install -y libgl1-mesa-dev xorg-dev libasound2-dev
    displayName: Install dev dependencies of pixel framework
  - task: GoTool@0
    inputs:
      version: "1.15"
  - task: Go@0
    inputs:
      command: "get"
      arguments: "-d"
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
  - task: Go@0
    inputs:
      command: "build"
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
  - task: CopyFiles@2
    inputs:
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop
