trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y libgl1-mesa-dev xorg-dev libasound2-dev
    displayName: Install dev libraries
  - task: GoTool@0
    displayName: Install go
    inputs:
      version: "1.21.5"    
  - task: Go@0
    displayName: 'go get'
    inputs:
      command: 'get'
      arguments: '-v all'
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"    
  - task: Go@0
    displayName: Build application
    inputs:
      command: 'build'
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"   
  - task: Go@0
    displayName: Test application
    inputs:
      command: 'test'
      arguments: '-v ./...'
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    env:
      sound: "no-fx;no-music"
