trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y libgl1-mesa-dev xorg-dev libasound2-dev
    displayName: Install dev libraries
  - task: GoTool@0
    inputs:
      version: "1.16"
    displayName: Install go
  - task: Go@0
    inputs:
      command: "get"
      arguments: "-d"
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    displayName: Install go modules
  - task: Go@0
    inputs:
      command: "build"
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    displayName: Build application
  - task: Go@0
    inputs:
      command: "test"
      arguments: "-v ./..."
      workingDirectory: "$(System.DefaultWorkingDirectory)/src"
    env:
      sound: "no-fx;no-music"
    displayName: Test application
