# This workflow will build and test to Retro-Carnage application.
#
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Install dev libraries
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev libasound2-dev
    - name: Install dependencies
      run: go get -d .
    - name: Build
      run: go build -v ./...
    - name: Download test assets
      shell: bash
      run: git clone https://github.com/Retro-Carnage-Team/retro-carnage-assets.git /tmp/retro-carnage-assets
    - name: Set environment variables for test execution      
      run: |
        echo "sound=no-fx;no-music" >> "$GITHUB_ENV"
        echo "RC-ASSETS=/tmp/retro-carnage-assets" >> "$GITHUB_ENV"
    - name: Test
      run: go test -v ./...
